import { AiGeneratedImage } from '../../../config/schema'
import db from '../../../config/dbConfig'
import { storage } from '../../../config/firebaseConfig'
import { getDownloadURL, ref, uploadString } from "firebase/storage";
import { NextResponse } from "next/server"
import Replicate from "replicate";

const replicate = new Replicate({
    auth: process.env.REPLICATE_API_TOKEN
});

export const POST = async (req)=> {

    const {imageUrl, roomType, designType, additionalRequirements, email} = await req.json()
    console.log(imageUrl , roomType, designType, additionalRequirements)

    // now we received all the required data (storedUrl and other all user's input)
    // then we have to convert the user's image to AI generated image
    // then the output url to base64 url because url generated by AI is temporary and expires in 24hrs 
    // then base64 url to firebase storage ////base64 is a way to represent image data in binary form once we convert to base64 we have AI image's data and can convert into permanent url and store directly in our storage
    // then store to our database
   try{
        const input = {
            image: imageUrl,
            prompt: `Transform this ${roomType} into a stunning ${designType} interior design. Maintain the room's basic structure and layout while completely redesigning the interior with ${designType} style elements.
            
            Key Requirements:
            - Room Type: ${roomType}
            - Design Style: ${designType}
            - Additional requirements: ${additionalRequirements}
            Focus on creating a cohesive, harmonious design that captures the essence of ${designType} style while making the space both beautiful and functional.`
        };
        
        // const output = await replicate.run(process.env.REPLICATE_AI_MODEL, { input });

        // const output = "https://replicate.delivery/xezq/Ouxry29sNA7KAtBwmiGeoD6lqWfaGaU8GbNLLWBe6zLeX0XXB/out.png"
        const base64Image = await convertImageToBase64(output)
        const fileName = Date.now()+'.png'
        const storageRef = ref(storage, 'ai-room-design/' + fileName)
        await uploadString(storageRef, base64Image, 'data_url')
        .then(res=>{console.log("File uploaded successfully...")})

        const downloadUrl = await getDownloadURL(storageRef)
        

        console.log(downloadUrl)
        const addImage = await db.insert(AiGeneratedImage).values({
            roomType,
            designType,
            aiImage: downloadUrl,
            originalImage: imageUrl,
            email

        }).returning()
        return NextResponse.json({
            success: true,
            message: "Data successfully added",
            downloadUrl,
            result: addImage[0]
        })

        

        // return NextResponse.json({"result" : downloadUrl})
 
        // return NextResponse.json({
        //     success: true,
        //     message: "Output successfully generated",
        //     output
        // }, {status:200})
        
   }
   catch(error) {
    return NextResponse.json({
        success: false,
        message: "Failed to generate output",
        error
    },{status: 500})
   }
   
}


const convertImageToBase64 = async(imageUrl)=> {
    const response = await fetch(imageUrl)
    const arrayBuffer = await response.arrayBuffer()
    const base64Raw = Buffer.from(arrayBuffer).toString('base64')
    return `data:image/png;base64,${base64Raw}`
}